language: go
go:
  - 1.12.x
  - 1.x

sudo: required

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - GO111MODULE=on
install: 
- sudo pip install pygments
- sudo pip install mkdocs
- sudo pip install mkdocs-material
- sudo pip install mkdocs-rtd-dropdown
script:
- git clean -f -d -x
- curl -sfL https://raw.githubusercontent.com/containous/structor/master/godownloader.sh | bash -s -- -b $GOPATH/bin v1.7.0
- sudo ./structor -o containous -r traefik --dockerfile-url="https://raw.githubusercontent.com/containous/traefik/master/docs.Dockerfile" --menu.js-url="https://raw.githubusercontent.com/containous/structor/master/traefik-menu.js.gotmpl" --exp-branch=master --debug

after_success:
- chmod +x build_docs.sh && ./build_docs.sh
