sudo: false
language: python
install:
- pip install pygments
- pip install mkdocs
- pip install mkdocs-material
script:
- git clean -f -d -x
after_success:
- git config user.name "adibrastegarnia"
- git config user.email "arastega@purdue.edu"
- git remote add gh-token "https://${gh-token}@github.com/multirepo-docs/root-docs.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;

