sudo: false
language: python
install:
- pip install pygments
- pip install mkdocs
- pip install mkdocs-material
script:
- git clean -f -d -x
after_success:
- chmod +x build_docs.sh && ./build_docs.sh
