apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fullname" . }}
  chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  release: "{{ .Release.Name }}"
  heritage: "{{ .Release.Service }}"
  labels:
    name: {{ template "fullname" . }}
  {{ if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{ end }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      ports:
        - name: gnmi
          containerPort: 10161
      readinessProbe:
        tcpSocket:
          port: 10161
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 10161
        initialDelaySeconds: 15
        periodSeconds: 20
      volumeMounts:
        - name: config
          mountPath: /etc/simulator/configs
          readOnly: true
  {{- if .Values.image.pullSecrets }}
  imagePullSecrets:
    {{- range .Values.image.pullSecrets }}
    - name: {{ . | quote }}
    {{- end }}
  {{- end }}
  volumes:
    - name: config
      configMap:
        name: {{ template "fullname" . }}-config
